// Styles for the voice room screen and its controls.

import { StyleSheet } from "react-native";
import { colors } from "@/src/theme";

export const styles = StyleSheet.create({
  top: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
  },
  headerButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chatUnreadBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 99,
    backgroundColor: colors.red,
    borderWidth: 2,
    borderColor: colors.bg,
  },
  chatUnreadText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  roomIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  kicker: {
    color: colors.cyan,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.7,
  },
  title: {
    color: colors.text,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
    marginTop: 1,
  },
  securityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  encryptionLabel: {
    flexShrink: 1,
    color: colors.faint,
    fontSize: 11,
    fontWeight: "700",
  },
  stateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: colors.panel2,
  },
  stateBadgeConnected: {
    backgroundColor: colors.greenSoft,
  },
  stateBadgeJoining: {
    backgroundColor: colors.cyanSoft,
  },
  stateDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.faint,
  },
  stateDotConnected: {
    backgroundColor: colors.green,
  },
  stateDotJoining: {
    backgroundColor: colors.cyan,
  },
  stateText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  stateTextConnected: {
    color: colors.green,
  },
  stateTextJoining: {
    color: colors.cyan,
  },

  scroll: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 106,
  },
  statusCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 12,
    marginBottom: 11,
    borderRadius: 16,
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.22)",
  },
  statusIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  statusCopy: {
    flex: 1,
  },
  statusTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  statusText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },
  warningCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    marginBottom: 11,
    borderRadius: 15,
    backgroundColor: "rgba(255,198,92,.07)",
    borderWidth: 1,
    borderColor: "rgba(255,198,92,.20)",
  },
  warningTitle: {
    color: colors.yellow,
    fontSize: 13,
    fontWeight: "900",
  },
  warningText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },
  errorCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    marginBottom: 11,
    borderRadius: 15,
    backgroundColor: colors.redSoft,
    borderWidth: 1,
    borderColor: "rgba(255,102,120,.25)",
  },
  errorCopy: {
    flex: 1,
  },
  errorTitle: {
    color: colors.red,
    fontSize: 13,
    fontWeight: "900",
  },
  errorText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },
  retry: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.panel2,
  },
  retryText: {
    color: colors.cyan,
    fontSize: 12,
    fontWeight: "900",
  },

  peopleHeading: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 5,
    marginBottom: 9,
  },
  sectionKicker: {
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: "900",
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
    marginTop: 2,
  },
  connectedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 99,
    backgroundColor: colors.greenSoft,
  },
  connectedPillDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.green,
  },
  connectedPillText: {
    color: colors.green,
    fontSize: 11,
    fontWeight: "900",
  },

  empty: {
    minHeight: 154,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 22,
    borderRadius: 19,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: "900",
    marginTop: 11,
  },
  emptyText: {
    maxWidth: 280,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 15,
    textAlign: "center",
    marginTop: 4,
  },
  people: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  person: {
    width: "48.8%",
    minHeight: 150,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 12,
    borderRadius: 18,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  personSelf: {
    borderColor: "rgba(95,225,255,.25)",
  },
  personSpeaking: {
    borderWidth: 2,
    borderColor: colors.green,
    backgroundColor: "rgba(67,226,154,.07)",
  },
  personPressed: {
    opacity: 0.78,
  },
  personCopy: {
    alignSelf: "stretch",
    alignItems: "center",
    minWidth: 0,
  },
  moreMenu: {
    position: "absolute",
    right: 16,
    bottom: 96,
    minWidth: 220,
    padding: 6,
    borderRadius: 18,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  personNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  personName: {
    flexShrink: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  youChip: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 99,
    backgroundColor: colors.cyanSoft,
  },
  youChipText: {
    color: colors.cyan,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  personMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 3,
  },
  activityHint: {
    color: colors.faint,
    fontSize: 13,
    marginTop: 3,
  },
  personIndicators: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statusIndicator: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  statusIndicatorRed: {
    backgroundColor: colors.redSoft,
  },
  statusIndicatorGreen: {
    backgroundColor: colors.greenSoft,
  },
  holdHint: {
    color: colors.faint,
    textAlign: "center",
    fontSize: 13,
    marginTop: 7,
  },

  videoSection: {
    marginTop: 18,
  },
  videoGrid: {
    gap: 9,
  },
  videoCard: {
    overflow: "hidden",
    borderRadius: 17,
    backgroundColor: "#03060D",
    borderWidth: 1,
    borderColor: colors.border,
  },
  video: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#02040A",
  },
  videoFooter: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  videoNameRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  videoName: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  videoMeta: {
    color: colors.cyan,
    fontSize: 13,
    fontWeight: "800",
  },

  settingsCard: {
    padding: 13,
    marginTop: 18,
    borderRadius: 18,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: "rgba(124,92,255,.32)",
  },
  settingsHeadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginBottom: 7,
  },
  settingsHeadingIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  settingsHeadingCopy: {
    flex: 1,
  },
  settingsTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  settingsHelp: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  settingsClose: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  inlineToggle: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  inlineToggleText: {
    flex: 1,
    color: colors.text,
    fontSize: 13,
    fontWeight: "700",
  },
  qualityLabel: {
    color: colors.muted,
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: "900",
    marginTop: 12,
    marginBottom: 7,
  },
  qualityRow: {
    flexDirection: "row",
    gap: 6,
  },
  qualityButton: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  qualityButtonActive: {
    backgroundColor: colors.cyanSoft,
    borderColor: "rgba(95,225,255,.40)",
  },
  qualityButtonText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  qualityButtonTextActive: {
    color: colors.cyan,
  },
  captureHint: {
    color: colors.faint,
    fontSize: 13,
    lineHeight: 13,
    marginTop: 9,
  },
  captureStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 9,
  },
  fullSettingsButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 10,
    borderRadius: 11,
    backgroundColor: colors.violetSoft,
  },
  fullSettingsText: {
    color: colors.violet,
    fontSize: 12,
    fontWeight: "900",
  },

  controls: {
    position: "absolute",
    alignSelf: "center",
    bottom: 22,
    maxWidth: "94%",
    padding: 7,
    borderRadius: 22,
    backgroundColor: colors.nav,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    shadowColor: "#000",
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  voiceControls: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 7,
  },
  control: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    backgroundColor: colors.panel2,
  },
  controlActive: {
    backgroundColor: colors.cyanSoft,
    borderColor: "rgba(95,225,255,.30)",
  },
  controlDanger: {
    backgroundColor: colors.redSoft,
    borderColor: "rgba(255,102,120,.20)",
  },
  controlDisabled: {
    opacity: 0.5,
  },
  controlPressed: {
    opacity: 0.72,
  },
  join: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 14,
    backgroundColor: colors.violet,
  },
  joinDisabled: {
    opacity: 0.55,
  },
  joinText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },

  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.overlay,
  },
  personSheet: {
    paddingHorizontal: 15,
    paddingTop: 9,
    paddingBottom: 20,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    gap: 8,
  },
  sheetGrabber: {
    width: 38,
    height: 4,
    alignSelf: "center",
    borderRadius: 99,
    backgroundColor: colors.faint,
    opacity: 0.5,
    marginBottom: 7,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 5,
  },
  sheetCopy: {
    flex: 1,
  },
  sheetName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  sheetMeta: {
    color: colors.cyan,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 2,
  },
  sheetCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  actionButton: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 10,
    borderRadius: 14,
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionButtonDanger: {
    backgroundColor: colors.redSoft,
    borderColor: "rgba(255,102,120,.24)",
  },
  actionIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  actionIconDanger: {
    backgroundColor: colors.redSoft,
  },
  actionLabel: {
    color: colors.text,
    fontSize: 11,
    fontWeight: "900",
  },
  actionDangerText: {
    color: colors.red,
  },
  actionDetail: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 12,
    marginTop: 2,
  },
  moderationBlock: {
    gap: 8,
    marginTop: 4,
  },
  moderationTitle: {
    color: colors.red,
    fontSize: 13,
    letterSpacing: 1.2,
    fontWeight: "900",
    marginTop: 3,
  },
});
