// Styles for the settings screen and its parts.

import { StyleSheet, Platform } from "react-native";
import { colors } from "@/src/theme";

export const styles = StyleSheet.create({
  hidden: {
    display: "none",
  },
  top: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  kicker: {
    color: colors.cyan,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  title: {
    color: colors.text,
    fontSize: 21,
    fontWeight: "900",
    marginTop: 1,
  },
  topIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.violetSoft,
  },

  scroll: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 38,
  },
  menuScroll: {
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 42,
  },
  menuSection: {
    marginTop: 20,
  },
  menuSectionTitle: {
    marginBottom: 8,
    paddingHorizontal: 4,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.35,
  },
  menuCard: {
    overflow: "hidden",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.panel,
  },
  menuRow: {
    minHeight: 72,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  menuRowLast: {
    borderBottomWidth: 0,
  },
  menuRowPressed: {
    backgroundColor: colors.violetSoft,
  },
  accountCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    marginBottom: 18,
    borderRadius: 18,
    backgroundColor: "rgba(124,58,237,0.22)",
    borderWidth: 1,
    borderColor: "rgba(196,181,253,0.3)",
  },
  accountRing: {
    padding: 2,
    borderRadius: 26,
    backgroundColor: colors.violet,
  },
  accountName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  logoutButton: {
    marginTop: 6,
    height: 46,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "rgba(239,68,68,0.12)",
    borderWidth: 1,
    borderColor: "rgba(248,113,113,0.3)",
  },
  logoutText: {
    color: "#FCA5A5",
    fontSize: 14,
    fontWeight: "900",
  },
  menuRowIcon: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  menuRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  menuRowTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  menuRowDetail: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 12,
  },
  menuRowValue: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  introCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    padding: 12,
    borderRadius: 17,
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.18)",
  },
  introIcon: {
    width: 43,
    height: 43,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  introTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  introText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 3,
  },

  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 21,
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  section: {
    color: colors.faint,
    fontSize: 10.5,
    letterSpacing: 1.6,
    fontWeight: "700",
    textTransform: "uppercase",
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  sectionRule: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
  },

  card: {
    padding: 12,
    borderRadius: 18,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  statusIcon: {
    width: 39,
    height: 39,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  label: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  help: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 12,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 99,
    backgroundColor: colors.panel2,
  },
  statusPillLive: {
    backgroundColor: colors.greenSoft,
  },
  statusPillDot: {
    width: 5,
    height: 5,
    borderRadius: 99,
    backgroundColor: colors.faint,
  },
  statusPillDotLive: {
    backgroundColor: colors.green,
  },
  statusPillText: {
    color: colors.faint,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.7,
  },
  statusPillTextLive: {
    color: colors.green,
  },
  primarySecondaryButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.24)",
  },
  primarySecondaryButtonText: {
    color: colors.cyan,
    fontSize: 12,
    fontWeight: "900",
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 13,
  },

  toggleRow: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingVertical: 7,
  },
  toggleIcon: {
    width: 35,
    height: 35,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },
  toggleCopy: {
    flex: 1,
    minWidth: 0,
  },
  toggleTitle: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 12,
  },
  toggleHelp: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 12,
    marginTop: 2,
  },

  choiceBlock: {
    paddingTop: 12,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  choiceHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  choiceTitle: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 13,
  },
  choiceHelp: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 12,
    marginTop: 2,
  },
  previewStack: {
    gap: 7,
    marginTop: 10,
  },
  previewButton: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewButtonActive: {
    backgroundColor: colors.cyanSoft,
    borderColor: "rgba(95,225,255,.30)",
  },
  radio: {
    width: 17,
    height: 17,
    borderRadius: 99,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.faint,
  },
  radioActive: {
    borderColor: colors.cyan,
  },
  radioInner: {
    width: 9,
    height: 9,
    borderRadius: 99,
    backgroundColor: colors.cyan,
  },
  previewButtonTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  previewButtonTitleActive: {
    color: colors.cyan,
  },
  previewButtonDetail: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
  },

  voiceActions: {
    flexDirection: "row",
    gap: 7,
    marginTop: 12,
  },
  voiceAction: {
    flex: 1,
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderRadius: 12,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
  },
  voiceActionActive: {
    backgroundColor: colors.redSoft,
    borderColor: "rgba(255,102,120,.24)",
  },
  voiceActionText: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 12,
  },
  voiceActionTextActive: {
    color: colors.red,
  },

  qualityRow: {
    flexDirection: "row",
    gap: 7,
    marginTop: 10,
  },
  qualityButton: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
  },
  qualityButtonActive: {
    backgroundColor: colors.cyanSoft,
    borderColor: "rgba(95,225,255,.34)",
  },
  qualityButtonText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
  },
  qualityButtonTextActive: {
    color: colors.cyan,
  },

  restartHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
  },
  restartHintText: {
    flex: 1,
    color: colors.cyan,
    fontSize: 13,
    lineHeight: 12,
  },
  micCheck: {
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.23)",
  },
  micCheckText: {
    color: colors.cyan,
    fontSize: 12,
    fontWeight: "900",
  },
  buttonDisabled: {
    opacity: 0.58,
  },
  micNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 9,
  },
  micNoticeSuccess: {},
  micNoticeText: {
    flex: 1,
    color: colors.yellow,
    fontSize: 13,
  },
  micNoticeTextSuccess: {
    color: colors.green,
  },

  syncError: {
    color: colors.yellow,
    fontSize: 12,
    lineHeight: 16,
    marginTop: 8,
  },
  timeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  timeField: {
    flex: 1,
  },
  timeLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 5,
  },
  timeInput: {
    minHeight: 42,
    borderRadius: 12,
    paddingHorizontal: 11,
    color: colors.text,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  timeHint: {
    color: colors.faint,
    fontSize: 12,
    marginTop: 6,
    marginBottom: 4,
  },
  hubRow: {
    paddingTop: 12,
    marginTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  hubName: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "900",
  },
  resetButton: {
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    marginTop: 8,
  },
  resetButtonText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },});
