// Styles for the Hub screen and its parts.

import { StyleSheet } from "react-native";
import { colors } from "@/src/theme";

export const styles = StyleSheet.create({
  draftTag: { color: colors.red, fontSize: 12, fontWeight: "800" },
  splitFill: { flex: 1 },
  splitRow: { flex: 1, flexDirection: "row" },
  splitList: { width: 360 },
  splitPane: { flex: 1, borderLeftWidth: StyleSheet.hairlineWidth, borderLeftColor: colors.border },
  splitEmpty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 10 },
  splitEmptyText: { color: colors.muted, fontSize: 14, fontWeight: "700" },
  roomSelected: { borderColor: colors.cyan },
  unreadBadge: { minWidth: 18, height: 18, paddingHorizontal: 5, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: colors.violet },
  unreadBadgeText: { color: "#FFFFFF", fontSize: 10.5, fontWeight: "900" },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  loadError: {
    color: colors.muted,
    textAlign: "center",
    marginTop: 10,
    lineHeight: 19,
  },
  retryButton: {
    marginTop: 14,
    minHeight: 42,
    paddingHorizontal: 18,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  retryButtonText: {
    color: colors.cyan,
    fontWeight: "800",
  },

  top: {
    minHeight: 82,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  hubIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  hubIconImage: {
    width: "100%",
    height: "100%",
  },
  hubIconFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.violet,
  },
  hubIconFallbackText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
  },
  topCopy: {
    flex: 1,
    minWidth: 0,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  title: {
    flexShrink: 1,
    color: colors.text,
    fontSize: 20,
    fontWeight: "900",
  },
  meta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 3,
  },
  manageButton: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },

  scroll: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 34,
  },

  descriptionCard: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 13,
    marginBottom: 12,
  },
  description: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },

  adminStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.22)",
    borderRadius: 16,
    padding: 12,
    marginBottom: 20,
  },
  adminStripIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
  },
  adminStripTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  adminStripText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },

  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 9,
    paddingHorizontal: 2,
  },
  sectionHeadingLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  sectionTitle: {
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 1.5,
    fontWeight: "900",
  },
  sectionRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  countBadge: {
    minWidth: 24,
    height: 20,
    paddingHorizontal: 7,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  countText: {
    color: colors.faint,
    fontSize: 12,
    fontWeight: "900",
  },
  sectionAdd: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
    borderWidth: 1,
    borderColor: "rgba(95,225,255,.20)",
  },
  sectionList: {
    gap: 8,
  },

  room: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 17,
    overflow: "hidden",
  },
  voiceRoom: {
    backgroundColor: colors.panel,
  },
  voiceConnected: {
    borderColor: "rgba(67,226,154,.45)",
    backgroundColor: colors.greenSoft,
  },
  roomMain: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    paddingLeft: 11,
    paddingVertical: 10,
  },
  roomPressed: {
    opacity: 0.78,
  },

  roomIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.cyanSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  voiceIcon: {
    backgroundColor: colors.violetSoft,
  },
  voiceIconConnected: {
    backgroundColor: "rgba(67,226,154,.14)",
  },

  roomCopy: {
    flex: 1,
    minWidth: 0,
  },
  roomNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  roomName: {
    flexShrink: 1,
    color: colors.text,
    fontSize: 14,
    fontWeight: "900",
  },
  privateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: colors.panel2,
  },
  privateText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  roomMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 4,
  },
  connectedText: {
    color: colors.green,
  },

  voiceOccupancy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  voiceAvatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  voiceAvatarWrap: {
    borderRadius: 999,
    borderWidth: 2,
    borderColor: colors.panel,
  },
  voiceAvatarOverlap: {
    marginLeft: -7,
  },
  voiceMore: {
    width: 24,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
    borderWidth: 2,
    borderColor: colors.panel,
  },
  voiceMoreText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "900",
  },
  voiceNames: {
    flex: 1,
    color: colors.faint,
    fontSize: 12,
    fontWeight: "700",
  },

  roomActions: {
    alignSelf: "stretch",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 9,
  },
  roomEmoji: { fontSize: 18 },
  iconGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  iconChoice: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconChoiceActive: { borderColor: colors.cyan, backgroundColor: colors.cyanSoft },
  iconChoiceText: { fontSize: 19, color: colors.text },
  iconInput: { marginTop: 8 },
  multilineInput: { minHeight: 90, textAlignVertical: "top", paddingTop: 12 },
  editRoomButton: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chevronWrap: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
  },

  connectedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(67,226,154,.12)",
  },
  connectedDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.green,
  },
  connectedBadgeText: {
    color: colors.green,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.7,
  },

  emptySection: {
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    backgroundColor: "rgba(13,20,37,.55)",
  },
  emptyText: {
    color: colors.faint,
    fontSize: 12,
  },

  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.overlay,
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  sheet: {
    maxHeight: "90%",
    minHeight: 420,
    backgroundColor: colors.bg,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: colors.borderStrong,
    overflow: "hidden",
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.borderStrong,
    alignSelf: "center",
    marginTop: 9,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 13,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetKicker: {
    color: colors.cyan,
    fontSize: 12,
    letterSpacing: 1.7,
    fontWeight: "900",
  },
  sheetTitle: {
    color: colors.text,
    fontSize: 19,
    fontWeight: "900",
    marginTop: 3,
  },
  sheetClose: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sheetScroll: {
    padding: 18,
    paddingBottom: 32,
  },

  fieldLabel: {
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 1.1,
    fontWeight: "900",
    marginBottom: 7,
    marginTop: 4,
  },
  input: {
    minHeight: 48,
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    borderRadius: 14,
    paddingHorizontal: 13,
    paddingVertical: 12,
    marginBottom: 15,
    fontSize: 14,
  },
  multiline: {
    minHeight: 90,
    textAlignVertical: "top",
  },

  permissionCard: {
    flexDirection: "row",
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 10,
  },
  permissionTitle: {
    color: colors.text,
    fontWeight: "800",
    fontSize: 12,
  },
  permissionText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 3,
  },

  segment: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 17,
  },
  segmentButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  segmentButtonActive: {
    backgroundColor: colors.cyanSoft,
    borderColor: "rgba(95,225,255,.35)",
  },
  segmentText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: colors.cyan,
  },

  sheetSectionTitle: {
    color: colors.muted,
    fontSize: 12,
    letterSpacing: 1.4,
    fontWeight: "900",
    marginTop: 6,
    marginBottom: 9,
  },
  createRoomCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 15,
    padding: 12,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 17,
  },
  createRoomIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  createRoomTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  createRoomText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },

  toggleCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 13,
    borderRadius: 15,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
  },
  toggleTitle: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "900",
  },
  toggleText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 3,
  },

  memberHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  memberSearch: { minHeight: 42, flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10, paddingHorizontal: 11, borderRadius: 13, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.border },
  memberSearchInput: { flex: 1, color: colors.text, fontSize: 12, paddingVertical: 0 },
  memberCount: {
    color: colors.faint,
    fontSize: 12,
    fontWeight: "800",
  },
  memberLoading: {
    minHeight: 80,
    alignItems: "center",
    justifyContent: "center",
  },
  memberList: {
    gap: 7,
    marginBottom: 16,
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 10,
    borderRadius: 14,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  memberRowSelected: {
    borderColor: "rgba(124,92,255,.45)",
    backgroundColor: colors.violetSoft,
  },
  memberName: {
    flex: 1,
    minWidth: 0,
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  memberCheck: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  memberCheckSelected: {
    backgroundColor: colors.violet,
    borderColor: colors.violet,
  },
  emptyMembers: {
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginBottom: 16,
  },
  emptyMembersTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: "800",
  },
  emptyMembersText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 3,
  },

  formError: {
    color: colors.red,
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 12,
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.violet,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  dangerButton: {
    minHeight: 46,
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    borderRadius: 14,
    backgroundColor: colors.redSoft,
    borderWidth: 1,
    borderColor: "rgba(255,102,120,.25)",
  },
  dangerButtonText: {
    color: colors.red,
    fontSize: 12,
    fontWeight: "900",
  },
});
