// Fixed app values: emoji and icon choices, page sizes, upload limits.

import type { Server } from "./types";

export const MAX_PROFILE_IMAGE_BYTES = 2 * 1024 * 1024;

export const EMOJI_GROUPS: Array<{ name: string; items: string[] }> = [
  {
    name: "Smileys",
    items: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "😂",
      "🤣",
      "😊",
      "🙂",
      "🙃",
      "😉",
      "😍",
      "🥰",
      "😘",
      "😎",
      "🤩",
      "🥳",
      "😏",
      "😴",
      "🤯",
      "😱",
      "😤",
      "😭",
      "😡",
      "🤬",
      "🤔",
      "🫡",
      "🫠",
      "🥶",
      "🥵",
    ],
  },
  {
    name: "Hands",
    items: ["👍", "👎", "👏", "🙌", "🫶", "🤝", "🙏", "👌", "✌️", "🤞", "🤟", "🤘", "👊", "✊", "💪", "🫵", "👋", "🤙"],
  },
  {
    name: "Gaming",
    items: [
      "🎮",
      "🕹️",
      "🏆",
      "🥇",
      "🎯",
      "🔥",
      "⚡",
      "💥",
      "🚀",
      "💀",
      "👑",
      "💎",
      "🛡️",
      "⚔️",
      "🔫",
      "🏎️",
      "🏁",
      "🎲",
      "🧠",
      "💯",
    ],
  },
  {
    name: "Hearts",
    items: ["❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💖", "💗", "💓", "💞", "💕", "💔", "❤️‍🔥"],
  },
  {
    name: "Objects",
    items: [
      "✅",
      "❌",
      "⚠️",
      "⭐",
      "✨",
      "🎉",
      "🎵",
      "🎧",
      "🎤",
      "📸",
      "📹",
      "📌",
      "🔒",
      "🔓",
      "💡",
      "🛠️",
      "⚙️",
      "📁",
      "📎",
      "🔗",
    ],
  },
  {
    name: "Nature",
    items: ["🌙", "☀️", "🌟", "🌌", "🌊", "❄️", "🌧️", "🌈", "🌲", "🌴", "🍀", "🌹", "🌸", "🍕", "🍔", "🍟", "☕", "🍺"],
  },
];

export const DEFAULT_ROOM_ICONS = ["💬", "🎮", "📣", "📌", "🛠️", "🎵", "🏆", "🎙️", "🔊", "🕹️", "✨", "🌙"];
export const REFERENCE_ROOM_ICONS = ["#", "♥", "🎮", "💗", "🔥", "📌", "🎙️", "🔊", "🎵", "🏆", "🌙", "✦"];
export const ROLE_ICON_CHOICES = [
  "👑",
  "🛡️",
  "⚔️",
  "⭐",
  "🔧",
  "🔨",
  "🎯",
  "🧭",
  "📢",
  "📚",
  "🎨",
  "🎮",
  "🏆",
  "💎",
  "🔥",
  "⚡",
  "🌙",
  "☀️",
  "🌊",
  "🌲",
  "🐉",
  "🦅",
  "🐺",
  "🤖",
  "👻",
  "💻",
  "🧪",
  "🎵",
  "❤️",
  "🚀",
  "🧠",
  "🔒",
];
export const SQUAD_LANGUAGE_OPTIONS = [
  "English",
  "Polish",
  "German",
  "French",
  "Spanish",
  "Italian",
  "Portuguese",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Czech",
  "Slovak",
  "Hungarian",
  "Romanian",
  "Greek",
  "Bulgarian",
  "Serbian",
  "Croatian",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Turkish",
  "Arabic",
  "Hebrew",
  "Persian",
  "Russian",
  "Ukrainian",
  "Hindi",
  "Bengali",
  "Urdu",
  "Chinese",
  "Japanese",
  "Korean",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Filipino",
];
// Matches the Worker's history page size; a full page means older messages may exist.
export const HISTORY_PAGE_SIZE = 100;

export const EMPTY_SERVER: Server = {
  id: 0,
  name: "No Hub Yet",
  icon: "+",
  ownerId: null,
  myRole: null,
  visibility: "private",
  memberCount: 0,
  onlineCount: 0,
  channels: [],
};
