// Styles for the room (channel) screen.

import { StyleSheet } from "react-native";
import { colors } from "@/src/theme";

export const styles = StyleSheet.create({
  actionBackdrop:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(2,5,12,.72)"},actionSheet:{padding:16,paddingBottom:28,borderTopLeftRadius:24,borderTopRightRadius:24,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.border},actionGrabber:{alignSelf:"center",width:42,height:4,borderRadius:99,backgroundColor:colors.border,marginBottom:13},emojiGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:12},emojiButton:{width:48,height:44,borderRadius:13,alignItems:"center",justifyContent:"center",backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.border},emojiButtonText:{fontSize:21},sheetAction:{minHeight:48,flexDirection:"row",alignItems:"center",gap:11,paddingHorizontal:11,borderRadius:13,backgroundColor:colors.panel2,marginTop:7},sheetDanger:{backgroundColor:colors.redSoft},sheetActionText:{color:colors.text,fontSize:13,fontWeight:"900"},
  reactionChipMine: { backgroundColor: "rgba(124,58,237,0.28)", borderColor: colors.violet },
  jumpLatest: { position: "absolute", right: 16, bottom: 92, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, height: 32, borderRadius: 16, backgroundColor: colors.violet },
  jumpLatestText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" },
  messageHighlight: { backgroundColor: "rgba(255,198,92,0.12)", borderRadius: 12 },
  pinnedTag: { flexDirection: "row", alignItems: "center", gap: 3, marginBottom: 2 },
  pinnedTagText: { color: colors.yellow, fontSize: 11, fontWeight: "800" },
  typingRow: { paddingHorizontal: 16, paddingVertical: 4 },
  typingText: { color: colors.muted, fontSize: 12, fontStyle: "italic" },
  forumPost: { gap: 6, padding: 10, borderRadius: 12, backgroundColor: colors.panel2, borderWidth: 1, borderColor: colors.border },
  forumTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  forumTags: { flexDirection: "row", flexWrap: "wrap", gap: 5 },
  forumTag: { color: colors.cyan, fontSize: 10, fontWeight: "800", paddingHorizontal: 7, paddingVertical: 2, borderRadius: 99, backgroundColor: colors.cyanSoft, overflow: "hidden" },
  editingBanner: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: colors.cyanSoft, borderTopWidth: 1, borderTopColor: colors.border },
  editingBannerText: { flex: 1, color: colors.text, fontSize: 12, fontWeight: "800" },
  editingCancel: { color: colors.cyan, fontSize: 12, fontWeight: "900" },
  replyingBanner: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: colors.cyanSoft, borderTopWidth: 1, borderTopColor: colors.border },
  replyingBannerText: { flex: 1, color: colors.text, fontSize: 12, fontWeight: "800" },
  flex: {
    flex: 1,
  },
  top: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  channelIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  topCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 16,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 3,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.green,
  },
  statusDotWaiting: {
    backgroundColor: colors.yellow,
  },
  status: {
    color: colors.green,
    fontSize: 13,
    fontWeight: "800",
  },
  statusWaiting: {
    color: colors.yellow,
  },
  hashBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel,
  },
  hashText: {
    color: colors.cyan,
    fontSize: 15,
    fontWeight: "900",
  },
  list: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 18,
  },
  listEmpty: {
    flexGrow: 1,
  },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingBottom: 80,
  },
  emptyIcon: {
    width: 56,
    height: 56,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 14,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 12,
    textAlign: "center",
    marginTop: 5,
  },
  dayDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    marginVertical: 14,
  },
  dayLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border,
  },
  dayText: {
    color: colors.faint,
    fontSize: 13,
    fontWeight: "800",
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
    paddingHorizontal: 2,
    marginBottom: 10,
  },
  messageRowGrouped: {
    marginTop: -4,
    marginBottom: 5,
  },
  messageRowOwn: {},
  avatarSpacer: {
    width: 36,
  },
  messageBody: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  messageBodyOwn: {
    backgroundColor: "rgba(124,92,255,.10)",
    borderColor: "rgba(124,92,255,.24)",
  },
  messageHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    marginBottom: 4,
  },
  username: {
    flexShrink: 1,
    color: colors.cyan,
    fontWeight: "900",
    fontSize: 13,
  },
  usernameOwn: {
    color: "#AFA3FF",
  },
  time: {
    color: colors.faint,
    fontSize: 11,
  },
  roleChip: {
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 99,
    backgroundColor: colors.violetSoft,
  },
  roleChipText: {
    color: "#B9AFFF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  messageText: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
  },
  replyReference: {
    maxWidth: "100%",
    borderLeftWidth: 2,
    borderLeftColor: colors.cyan,
    paddingLeft: 7,
    marginBottom: 7,
  },
  replyReferenceText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 14,
  },
  mention: {
    color: colors.cyan,
    fontWeight: "800",
  },
  mentionMine: {
    color: colors.lilac,
    fontWeight: "900",
    backgroundColor: "rgba(124,92,255,.18)",
  },
  attachment: {
    width: "100%",
    minWidth: 0,
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    padding: 8,
    borderRadius: 12,
    backgroundColor: colors.panel2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  attachmentIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.cyanSoft,
  },
  attachmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  attachmentName: {
    color: colors.text,
    fontSize: 12,
    fontWeight: "800",
  },
  attachmentMeta: {
    color: colors.faint,
    fontSize: 13,
    marginTop: 2,
  },
  reactions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    marginTop: 7,
  },
  reactionChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 99,
    backgroundColor: colors.panel2,
  },
  reactionEmoji: {
    fontSize: 13,
  },
  reactionCount: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  edited: {
    color: colors.faint,
    fontSize: 13,
    marginTop: 5,
  },
  groupedTime: {
    color: colors.faint,
    fontSize: 11,
    marginTop: 5,
  },
  composerShell: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 9,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.bg,
  },
  composer: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    padding: 6,
    borderRadius: 18,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderStrong,
  },
  plusButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.panel2,
    opacity: 0.68,
  },
  input: {
    flex: 1,
    minHeight: 36,
    maxHeight: 120,
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 2,
    paddingVertical: 8,
  },
  send: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.violet,
  },
  sendDisabled: {
    opacity: 0.34,
  },
  composerHint: {
    color: colors.faint,
    fontSize: 13,
    lineHeight: 11,
    textAlign: "center",
    marginTop: 5,
  },});
